### ISSUE TITLE
如何在悬浮窗内修改悬浮窗大小

### ISSUE THREAD

**Issue by 2971026328** [qiuxiang/flutter-android-window#25]
在组件里面的按钮用android_window.resize(600, 400)报错如下
E/flutter (13282): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (13282): #0      MainApi.post (package:android_window/pigeon.g.dart:107:7)
E/flutter (13282): <asynchronous suspension>
E/flutter (13282): #1      post (package:android_window/main.dart:59:20)
E/flutter (13282): <asynchronous suspension>

**Comment by qiuxiang** [comment]
调这个方法
```dart
AndroidWindow.resize(600, 400)
```

**Comment by 2971026328** [comment]
好的谢谢，我尝试一下非常感谢

**Comment by 2971026328** [comment]
成功了，研究了一下午，都用上Isolate通信没解决哈哈，感谢大佬

**Comment by qiuxiang** [comment]
仅通过 dart 是没法通信的，因为两个 flutter 分别运行再不同的 engine 里

**Comment by 2971026328** [comment]
了解，谢谢大佬科普
