### ISSUE TITLE
在使用过程中，出现闪退

### ISSUE THREAD

**Issue by Jun-r** [qiuxiang/flutter-android-window#5]
大佬你好，我在使用的时候，不清楚是不是JAVA版本不兼容，还是什么，昨天已经已经成功可以显示窗口，晚上mac升级了一下，运行就报以下错误
JAVA版本是：1.8.311.11
这是我的Flutter版本信息
[✓] Flutter (Channel master, 2.6.0-12.0.pre.840, on macOS 12.0.1 21A559 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-12.0.pre.840 at /Users/hejun/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 08233cb384 (2 days ago), 2021-11-26 13:38:03 -0500
    • Engine revision b12306aef4
    • Dart version 2.16.0 (build 2.16.0-54.0.dev)
    • DevTools version 2.8.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
    
 报错如下
 java.lang.ClassCastException: qiuxiang.android_window.WindowService cannot be cast to android.app.Activity
        at io.flutter.embedding.android.FlutterView.createWindowInfoRepo(FlutterView.java:458)
        at io.flutter.embedding.android.FlutterView.onAttachedToWindow(FlutterView.java:478)
        at android.view.View.dispatchAttachedToWindow(View.java:20102)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3619)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2549)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8884)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:911)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by qiuxiang** [comment]
你的 flutter 是 dev 或 beta 的吧，我只在 stable 测过

**Comment by Jun-r** [comment]
谢谢大佬的回答，我切换了stable已经ok了，我最开始我的dev是没有报错且正常运行窗口，可能是我后面又flutter upgrade了下最新版本，最新的dev确实有报错，不过没关系，用stable就可以了
